### ISSUE TITLE
Shift SDF implementation to a new and better Tiny SDF implementation

### ISSUE THREAD

**Issue by gauravgrover95** [HelikarLab/ccNetViz#10]
I have found this [Github Library](https://github.com/mapbox/tiny-sdf). This seems to be a better and improved version of SDF algorithm we are using.

We have to check the compatability and try incorporating this algorithm in our implementation.

**Comment by saskaale** [comment]
This library looks like it is rendering the SDF in the pure JS rendering into HTML canvas. Is there any possibility to implement this directly inside WebGL ?

**Comment by gauravgrover95** [comment]
Hi @saskaale,

I am looking into it. But following quote was written in the second line of its documentation due to which I think, we will be able to implement it inside ccNetViz.

Quote:

> This is very useful for rendering text with WebGL.

If I face any issue, I will reply here. 

Thanks.

**Comment by gauravgrover95** [comment]
Hi @saskaale,

I understood your concern and I reviewed the code of tiny-sdf. Please check that the author has made a demo file in which he has used both _canvas-2d_ as well as _experimental-webGl_ context to show the implementation of the library. So, I don't think we will have to go through the hassle of porting the algorithm into webgl.

You can view the demo by clicking [here](https://mapbox.github.io/tiny-sdf/) and the code [here](https://github.com/mapbox/tiny-sdf/blob/master/index.html). Please observe from the code that the second canvas box fetched inside variable _canvas2_ on line number #115 is using webgl implementation.

Meanwhile, I am also reading and understanding the code for sdf implementation in ccNetViz found in /src/text/ folder. 

Can you please guide me that what functions I will need to edit and in what function we can inject algorithmic code directly from 'tiny-sdf'?

Thanks.

**Comment by saskaale** [comment]
Hello @gauravgrover95 . This example looks nice ! As long as the texture would be rendered just once at start ( O(1) complexity ) and after that would be used to render text character-by-character ( it is currently implemnted in ccNetViz ) it should be fine!

**Comment by gauravgrover95** [comment]
7ac1ae35f978aa6e6fb37b367ca6e786e390b335 implements the sdf algorithm. Some refactoring can be done though.
