### ISSUE TITLE
`graph.reflow` is not a function

### ISSUE THREAD

**Issue by achillesrasquinha** [HelikarLab/ccNetViz#141]
While attempting to try this example - http://helikarlab.github.io/ccNetViz/examples/interactivity_hover.html I get `graph.reflow` is not a function.

**Comment by saskaale** [comment]
please provide full stacktrace

**Comment by achillesrasquinha** [comment]
Looks like this doesn't work in case of multilevel graphs?

**Comment by saskaale** [comment]
I was not able to simulate. Can you please provide working example alongside with the full stacktrace?

**Comment by achillesrasquinha** [comment]
Closing. This works within latest master banch.
