### ISSUE TITLE
High Resolution Graph Image Export

### ISSUE THREAD

**Issue by HelikarLabPersonal** [HelikarLab/ccNetViz#147]
CCNetViz currently supports the download of graphs as a png file only, with limited resolution. We are looking to develop support to enable the download of high-resolution images of graphs in various file formats, including .png, .jpg., and potential secondary implementation of the rendering engine in SVG.

A potential solution would be to develop additional renderers (SVG and/or Canvas) that would be called and used when a network export function is called.

**Comment by canerakdas** [comment]
#150
