### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by saskaale** [HelikarLab/ccNetViz#15]
1) Performance benchmark 
     -- rendering time, layout computation time for various networks of increasing sizes
     -- see https://github.com/HelikarLab/ccNetViz/tree/master/src/layout for all implemented layouts
     -- see https://github.com/HelikarLab/ccNetViz/tree/master/examples/data for graphs ~( you can even add / create new ones )
2) Feature comparison table that would illustrate how ccNetViz fits in with other network visualization tools (layouts, node/edge coloring etc. )

The performance benchmark would be done for the same net visualization tools that would be compared in the feature comparison table.

Software to compare ccNetViz against:
slim D3 plot of the implemented layouts. (I can implement this)
Cytoscape.JS
SigmaJS
JSNetworkX
other possible softwares

**Comment by himanshuc3** [comment]
Hi, I would love to work on this project and make it better. Also, I would love to make a few visualization layouts. Is it possible?
