### ISSUE TITLE
Nodes show up as black marks on home page while using Firefox

### ISSUE THREAD

**Issue by mpearson12** [HelikarLab/ccNetViz#17]
The nodes should not be black marks
![](https://git.unl.edu/helikarlab/cellcollective/uploads/9b5528a1f378de2d277b8adcfca065cd/Screenshot_2018-06-15_13.08.25.png)

**Comment by achillesrasquinha** [comment]
@gauravgrover95 Hi, are you able to replicate this?

**Comment by gauravgrover95** [comment]
No, I was not able to reproduce it by going to the https://cellcollective.org and then pushing the 'try without registration' button. But yes, I have observed the similar behavior while developing the library in Firefox Quantum browser 61.0 (64-bit).

Can you share your version of the Firefox and the error from the console of Firefox dev-tools?

**Comment by mpearson12** [comment]
I actually cant get it to replicate anymore so maybe my firefox just needed updating?

**Comment by gauravgrover95** [comment]
@mpearson12  Can you check again and report with the your OS and Firefox version?

**Comment by hjhimanshu01** [comment]
@gauravgrover95 , I'm facing the same issue
