### ISSUE TITLE
Random user inputs against config option of layout name is not handled

### ISSUE THREAD

**Issue by gauravgrover95** [HelikarLab/ccNetViz#21]
#### Description 
User is supposed to provide the layout name to the library manually like:

`graph.set(nodes, edges, "force"); .`

Leaving responsibility to the user to provide the correct layout name against in the configuration file could be a bad practice. If the layout name is not correct, library throws an error as below:

![error](https://user-images.githubusercontent.com/13467940/43476436-35ca6adc-9516-11e8-877e-6b2af7370c72.png)

Possible fixes:

1. stop the execution of library by throwing a proper error that will guide user to fix the name
2. choose render a chosen default layout
3. We can do both 

Corresponding code files: [Code file 1](https://github.com/HelikarLab/ccNetViz/blob/master/src/layer.js#L357
) and [Code File 2](https://github.com/HelikarLab/ccNetViz/blob/master/src/layout/layout.js)

**Comment by saskaale** [comment]
Hello Gaurav,
I would do the first solution, which would throw an error. Chosing default layout ( alongside with printing out is warning ) is also possible option, but the user should be overall responsible for putting the correct layout name.

Let's do the first option.

**Comment by gauravgrover95** [comment]
Fixed with the implementation of background layout computation's new code corresponding to #9

**Comment by gauravgrover95** [comment]
@saskaale Can you kindly merge the code and close this issue?
