### ISSUE TITLE
Adding prettier

### ISSUE THREAD

**Issue by himanshuc3** [HelikarLab/ccNetViz#29]
I think to generalize the code standard and white spacing we could add prettier. I could do that if needed. Open to suggestions!

**Comment by gauravgrover95** [comment]
I think we can definitely use this but it would be better if we focus on this in the later stages of the project. 

Currently, the opened Github issues and the [suggested task lists](http://helikarlab.org/GSoC2018.html) are of relatively more importance for improving the library.

**Comment by shadxx7** [comment]
#57 adds prettier. Can be closed now.
