### ISSUE TITLE
Add >>npm start<< command for better user-friendliness

### ISSUE THREAD

**Issue by saskaale** [HelikarLab/ccNetViz#32]
This command would internally 

 1) run the simple web server ( for example https://www.npmjs.com/package/http-server ) and 
 2) Open browser window with examples directory ( parameter -o in the http-server package )

additional work required:
  - add simple index page into the examples directory whichs allows users to redirect to each example
  - document these steps needed for showing in the Readme.md page
      a) download with git clone
      b) yarn install
      c) yarn build
      d) yarn start

**Comment by promehul** [comment]
@saskaale  Since no work has been done so far, can I work on this issue? I really think I can do it

**Comment by AyoubEd** [comment]
I implemented it actually, but I'm having an issue with http-server. Even after using -o to point to the target directory, it still shows the root dir.

**Comment by saskaale** [comment]
Hello @AyoubEd . This looks like the OS issue. I would suggest you to try some different library than http-server (you can use the https://www.npmjs.com/package/local-web-server, or different one). 

If you would not succeed even then I would suggest to simply move the html navigation page from examples directory into the root one.


Thanks for your work !

**Comment by hjhimanshu01** [comment]
@saskaale , if nobody is working on this issue , I did setup my local dev server using http-server , would like to submit a PR to start a server easily using "npm run start" . May I?

**Comment by saskaale** [comment]
Hello @hjhimanshu01 thank you for your PR ! I left you some comments there.

**Comment by hjhimanshu01** [comment]
@saskaale , fixed!
