### ISSUE TITLE
No "ccNetViz.min.js" available in /dist directory as illustrated in 'basic example' section of /README.md

### ISSUE THREAD

**Issue by gauravgrover95** [HelikarLab/ccNetViz#5]
In the documentation file /README.md. Maybe there is a simple spelling error or in the latest build, we have missed the minified compilation of the source code. 

Please refer the code below: 

**README.md**
```
<!-- Basic Example -->

...
... 
<style type="text/css">
    #container {
      width: 500px;
      height: 500px;
    }
  </style>
  <script src="dist/ccNetViz.min.js" ></script>     <!-- ERROR -->
</head>
<body>
  <canvas id="container"/>
...
...
```

**Comment by saskaale** [comment]
Seems like old code from previous version. Can you please fix?
