### ISSUE TITLE
Errors while importing to ReactJS

### ISSUE THREAD

**Issue by shadxx7** [HelikarLab/ccNetViz#51]
Getting the following errors while importing ccNetViz (latest version from the github repo) in ReactJS (Using eslint, create-react-app configuration):

![ccNetViz-errors](https://user-images.githubusercontent.com/22408263/59054384-a245ac80-88a4-11e9-9101-eb4eb254ba9d.jpg)

**Comment by shadxx7** [comment]
Fix for the issue: 
to add the latest version of ccNetViz to a react application:
```bash
git clone https://github.com/HelikarLab/ccNetViz.git
cd ccNetViz
pwd # this will output the path to the repo
```
Copy the path and go to your react project folder and run the following:

```bash
yarn add <the_path_you_copied>
```
now you can import ccNetViz like you did when using the one on npm.

**Comment by saskaale** [comment]
https://github.com/saskaale/react-ccNetViz
