### ISSUE TITLE
Graphs not rendering properly

### ISSUE THREAD

**Issue by aman-dave** [HelikarLab/ccNetViz#55]
The graphs on the ccNetViz website, along with cell collective are not being rendered properly on the browser. The issue is with hardware acceleration when rendering such graphs. Sometimes the operating systems have low compatibility with certain hardware.

Current Operating System: Linux Mint 19 Tara
GPU: Nvidia GTX 1050

![Screenshot from 2019-06-13 10-18-59](https://user-images.githubusercontent.com/39700577/59447100-5f458500-8e20-11e9-8f38-7db6031854f4.png)

![Screenshot from 2019-06-13 10-19-18](https://user-images.githubusercontent.com/39700577/59447119-65d3fc80-8e20-11e9-8fe1-46d479c2444e.png)

**Comment by wizArD-1910** [comment]
To solve the issue:

Go to the Chrome Setting -> Advanced Setting -> Turn off the Hardware Acceleration

**Comment by saskaale** [comment]
Hey @wizArD-1910, what is your Chrome version ?

**Comment by wizArD-1910** [comment]
> Hey @wizArD-1910, what is your Chrome version ?

Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by saskaale** [comment]
Hello @wizArD-1910 , can you please check whether this happens in the latest version of ccNetViz ?


Ales

**Comment by saskaale** [comment]
probably webgl error
